let block1 = Block()
world.place(block1, atColumn: 3, row: 3)
    /*
let character = Character()
world.place(character, facing: south, atColumn: 0, row: 5)
character.moveForward()
 */
move(distance: 2)
turnLeft()
move(distance: 3)
turnRight()
move(distance: 3)
turnLeft()
move(distance: 2)
toggleSwitch()
